### ISSUE TITLE
Local RStudio setup EE error

### ISSUE THREAD

**Issue by sebhaan** [Sydney-Informatics-Hub/dataharvester#5]
── Welcome to AgReFed Data-Harvester ────────────────────────────────────────────

ℹ Checking if dataharvesteR has been set up appropriately
ℹ Check Python/conda install
✔ conda binary: /Users/seb/mambaforge/bin/conda
✔ conda env: geopy

ℹ Checking package versions
✔ all packages validated
ℹ Set up Earth Engine API access
Error in py_module_import(module, convert = convert) : 
  TypeError: 'numpy._DTypeMeta' object is not subscriptable

**Comment by januarharianto** [comment]
This was an error if the package were installed from `"januarharianto/dataharvester"`. Error occured because I stupidly did not update the install instructions in README after forking the project to SIH. Should not be an issue in v0.0.7, closing for now.
